server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waber_match
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: match-service

waber:
  match:
    schedule:
      corePool: 8
      rescheduleDelayTimeInMs: 3000

